name: Mirror to Codeberg
on: 
  push:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          CB_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg https://zenyhoj:${CB_TOKEN}@codeberg.org/zenyhoj/bwd-online.git
          git push --prune codeberg +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
